container.c File Reference
#include `head.h`
Functions
void initContainer (int width, int height, container *item)
container randomPiece ()
container createU ()
container createL1 ()
container createL2 ()
container createCross ()
container createDot ()
container createLine ()
void deleteContainer (container *item)
int checkCollision (container *grid, container *piece, int x, int y)
void place (container *grid, container *piece, int x, int y)
Function Documentation
checkCollision()
int checkCollision (container * grid, container * piece, int x, int y)
Definition at line 123 of file container.c.
References container::data, container::len, and container::size.
Referenced by main().
                                                                     {
    for (int i = 0; i < piece->size/piece->len; i++) {
        for (int j = 0; j < piece->len; j++) {
            if (i+y < 0 || i+y >= (grid->size/grid->len) || j+x < 0 || j+x >= grid->
      len) {
                return 1;
            }
            if (grid->data[((i+y)*grid->len)+j+x] && piece->data[(i*piece->
      len)+j]) {
                return 1;
            }
        }
    }
    return 0;
}
createCross()
container createCross ()
Definition at line 82 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                       {
    container piece;
    char color = rand()%6+1;
    initContainer(5, 5, &piece);
    piece.data[2] = color;
    piece.data[7] = color;
    piece.data[10] = color;
    piece.data[11] = color;
    piece.data[12] = color;
    piece.data[13] = color;
    piece.data[14] = color;
    piece.data[17] = color;
    piece.data[22] = color;
    piece.data[24] = 0;
    return piece;
}
createDot()
container createDot ()
Definition at line 100 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                     {
    container piece;
    char color = rand()%6+1;
    initContainer(1, 1, &piece);
    piece.data[0] = color;
    return piece;
}
createL1()
container createL1 ()
Definition at line 58 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                    {
    container piece;
    char color = rand()%6+1;
    initContainer(3, 2, &piece);
    piece.data[0] = color;
    piece.data[3] = color;
    piece.data[4] = color;
    piece.data[5] = color;
    return piece;
}
createL2()
container createL2 ()
Definition at line 70 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                    {
    container piece;
    char color = rand()%6+1;
    initContainer(3, 2, &piece);
    piece.data[2] = color;
    piece.data[3] = color;
    piece.data[4] = color;
    piece.data[5] = color;
    return piece;
}
createLine()
container createLine ()
Definition at line 109 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                      {
    container piece;
    char color = rand()%6+1;
    initContainer(1, 2, &piece);
    piece.data[0] = color;
    piece.data[1] = color;
    return piece;
}
createU()
container createU ()
Definition at line 42 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                   {
    char color;
    container piece;
    color = rand()%6+1;
    initContainer(3, 3, &piece);
    piece.data[0] = color;
    piece.data[2] = color;
    piece.data[3] = color;
    piece.data[5] = color;
    piece.data[6] = color;
    piece.data[7] = color;
    piece.data[8] = color;
    return piece;
}
deleteContainer()
void deleteContainer (container * item)
Definition at line 119 of file container.c.
References container::data.
                                      {
    free(item->data);
}
initContainer()
void initContainer (int width, int height, container * item)
Definition at line 3 of file container.c.
References container::data, container::len, and container::size.
Referenced by createCross(), createDot(), createL1(), createL2(), createLine(), createU(), and main().
                                                          {
    item->len = width;
    item->size = width * height;
    item->data = malloc(item->size * sizeof(char));
    for (int i = 0; i < item->size; ++i)
    {
        item->data[i] = 0;
    }
}
place()
void place (container * grid, container * piece, int x, int y)
Definition at line 137 of file container.c.
References container::data, container::len, and container::size.
Referenced by main().
                                                              {
    for (int i = 0; i < piece->size/piece->len; i++) {
        for (int j = 0; j < piece->len; j++) {
            if (piece->data[(i*piece->len)+j] != 0) {
                grid->data[((i+y)*grid->len)+j+x] = piece->data[(i*piece->
      len)+j];
            }
        }
    }
}
randomPiece()
container randomPiece ()
Definition at line 13 of file container.c.
References createCross(), createDot(), createL1(), createL2(), createLine(), and createU().
Referenced by main().
                       {
    container piece;
    srand(time(NULL));
    int random = rand() % 6;
    switch (random){
        case 0 :
            piece = createU();
            return piece;
        case 1 :
            piece = createL1();
            return piece;
        case 2 :
            piece = createL2();
            return piece;
        case 3 :
            piece = createCross();
            return piece;
        case 4:
            piece = createDot();
            return piece;
        case 5 :
            piece = createLine();
            return piece;
        default :
            printf("Error : could not generate cooresponding piece for int : %d \n", random);
            exit(0);
    }
}