head.h File Reference
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct container
Macros
#define WIDTH 25
#define HEIGHT 20
Functions
int * detectRow (container *grid)
char fullRow (container *grid, int index)
void deleteRow (container *grid, int *indexList)
int * detectCol (container *grid)
char fullCol (container *grid, int index)
void deleteCol (container *grid, int *indexList)
void gravity (container *grid, int *index_list_line, int *index_list_col)
void update (container *grid)
void initContainer (int width, int height, container *item)
container randomPiece ()
container createU ()
container createL1 ()
container createL2 ()
container createCross ()
container createDot ()
container createLine ()
void deleteContainer (container *item)
int checkCollision (container *grid, container *piece, int x, int y)
void place (container *grid, container *piece, int x, int y)
void display (container *grid)
void rotate_90 (container *piece)
void rotate_180 (container *piece)
Macro Definition Documentation
HEIGHT
#define HEIGHT 20
Definition at line 12 of file head.h.
Referenced by main().
WIDTH
#define WIDTH 25
Definition at line 11 of file head.h.
Referenced by main().
Function Documentation
checkCollision()
int checkCollision (container * grid, container * piece, int x, int y)
Definition at line 123 of file container.c.
References container::data, container::len, and container::size.
Referenced by main().
                                                                     {
    for (int i = 0; i < piece->size/piece->len; i++) {
        for (int j = 0; j < piece->len; j++) {
            if (i+y < 0 || i+y >= (grid->size/grid->len) || j+x < 0 || j+x >= grid->
      len) {
                return 1;
            }
            if (grid->data[((i+y)*grid->len)+j+x] && piece->data[(i*piece->
      len)+j]) {
                return 1;
            }
        }
    }
    return 0;
}
createCross()
container createCross ()
Definition at line 82 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                       {
    container piece;
    char color = rand()%6+1;
    initContainer(5, 5, &piece);
    piece.data[2] = color;
    piece.data[7] = color;
    piece.data[10] = color;
    piece.data[11] = color;
    piece.data[12] = color;
    piece.data[13] = color;
    piece.data[14] = color;
    piece.data[17] = color;
    piece.data[22] = color;
    piece.data[24] = 0;
    return piece;
}
createDot()
container createDot ()
Definition at line 100 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                     {
    container piece;
    char color = rand()%6+1;
    initContainer(1, 1, &piece);
    piece.data[0] = color;
    return piece;
}
createL1()
container createL1 ()
Definition at line 58 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                    {
    container piece;
    char color = rand()%6+1;
    initContainer(3, 2, &piece);
    piece.data[0] = color;
    piece.data[3] = color;
    piece.data[4] = color;
    piece.data[5] = color;
    return piece;
}
createL2()
container createL2 ()
Definition at line 70 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                    {
    container piece;
    char color = rand()%6+1;
    initContainer(3, 2, &piece);
    piece.data[2] = color;
    piece.data[3] = color;
    piece.data[4] = color;
    piece.data[5] = color;
    return piece;
}
createLine()
container createLine ()
Definition at line 109 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                      {
    container piece;
    char color = rand()%6+1;
    initContainer(1, 2, &piece);
    piece.data[0] = color;
    piece.data[1] = color;
    return piece;
}
createU()
container createU ()
Definition at line 42 of file container.c.
References container::data, and initContainer().
Referenced by randomPiece().
                   {
    char color;
    container piece;
    color = rand()%6+1;
    initContainer(3, 3, &piece);
    piece.data[0] = color;
    piece.data[2] = color;
    piece.data[3] = color;
    piece.data[5] = color;
    piece.data[6] = color;
    piece.data[7] = color;
    piece.data[8] = color;
    return piece;
}
deleteCol()
void deleteCol (container * grid, int * indexList)
Definition at line 108 of file update.c.
References container::data, container::len, and container::size.
Referenced by update().
                                                {
    int actual, max_len, max_size, max_size1, i, j;
    char *save_data;
    //Sauvegarde
    save_data = grid->data;
    max_len = grid->len;
    max_size1 = grid->size;
    max_size = index_list[0];
    for(i=1; i<max_size; ++i){
        actual = index_list[i];
        for(j=actual; j< max_size1; j += max_len){
            save_data[j] = 0;
        }
    }
}
deleteContainer()
void deleteContainer (container * item)
Definition at line 119 of file container.c.
References container::data.
                                      {
    free(item->data);
}
deleteRow()
void deleteRow (container * grid, int * indexList)
Definition at line 44 of file update.c.
References container::data, and container::len.
Referenced by update().
                                                {
    int actual, max_len, max_size, i, j;
    char *save_data;
    //Sauvegarde
    save_data = grid->data;
    max_len = grid->len;
    max_size = index_list[0];
    for(i=1; i<max_size; ++i){
        actual = index_list[i];
        for(j=actual; j< actual + max_len; ++j){
            save_data[j] = 0;
        }
    }
}
detectCol()
int* detectCol (container * grid)
Definition at line 66 of file update.c.
References fullCol(), and container::len.
Referenced by update().
                               {
    int *index, actual, max_len, i;
    //save
    max_len = grid->len;
    //Index
    actual = 1;
    index = malloc((max_len+1)*sizeof(int));
    for(i=0; i<max_len; ++i){
        if(fullCol(grid, i)){
            index[actual] = i;
            ++actual;
        }
    }
    index[0] = actual;
    return realloc(index, actual);
}
detectRow()
int* detectRow (container * grid)
Definition at line 4 of file update.c.
References fullRow(), container::len, and container::size.
Referenced by update().
                               {
    int *index, actual, max_len, max_size, i;
    //Sauvegarde
    max_len = grid->len;
    max_size = grid->size;
    //Index
    actual = 1;
    index = malloc((max_size/max_len + 1)*sizeof(int));
    for(i=0; i<max_size; i += max_len){
        if(fullRow(grid, i)){
            index[actual] = i;
            ++actual;
        }
    }
    index[0] = actual;
    return realloc(index, actual);
}
display()
void display (container * grid)
Definition at line 3 of file user.c.
References container::data, container::len, and container::size.
Referenced by main().
                             {
    char *toShow = "36m";
    int i;
    for (i = 0; i < grid->len+2; i++) {
        printf("-");
    }
    printf("\n|");
    for (i = 0; i < grid->size; i++) {
        if (i % grid->len == 0 && i != 0) {
            printf("|%d\n|", (i/grid->len)-1); // Erreur ! Affichage de 23 puis 25 dans les deux
       dernières lignes de la zone de jeu, et même phénomène pour la preview pièce
        }
        switch (grid->data[i]) {
            case 2:
                toShow = "31m";
                break;
        }
        if (grid->data[i] > 0){
            printf("\033[%sX", toShow);
        }else{
            printf(" ");
        }
    }
    printf("|%d\n",i/grid->len-1);
    for (i = 0; i < grid->len+2; i++) {
        printf("-");
    }
    printf("\n");
}
fullCol()
char fullCol (container * grid, int index)
Definition at line 89 of file update.c.
References container::data, container::len, and container::size.
Referenced by detectCol().
                                        {
    int max_size, max_len, j;
    char* save_data;
    //save
    save_data = grid->data;
    max_size = grid->size;
    max_len = grid->len;
    for(j=index; j<max_size; j+=max_len){
        if(save_data[j] == 0) break;
    }
    if(j >= max_size){
        return 1;
    }
    return 0;
}
fullRow()
char fullRow (container * grid, int index)
Definition at line 27 of file update.c.
References container::data, and container::len.
Referenced by detectRow().
                                        {
    int max_len, j;
    char* save_data;
    save_data = grid->data;
    max_len = grid->len;
    for(j=index; j< index + max_len; ++j){
        if(save_data[j] == 0) break;
    }
    if(j == index + max_len){
        return 1;
    }
    return 0;
}
gravity()
void gravity (container * grid, int * index_list_line, int * index_list_col)
Definition at line 130 of file update.c.
References container::data, container::len, and container::size.
Referenced by update().
                                                                       {
    int max_len, max_size, save_size, save_index, i, j, k;
    char *save_data;
    //Save
    save_data = grid->data;
    max_size = grid->size;
    max_len = grid->len;
    //Update row
    save_size = index_list_row[0];
    for(i=1; i<save_size; ++i){
        for(j=index_list_row[i]-1; j>=0; --j){
            save_data[j+max_len] = save_data[j];
            save_data[j] = 0;
        }
    }
    //Update Col
    save_size = index_list_col[0];
    for(i=save_size-1; i>=1; --i){
        save_index = index_list_col[i];
        for(j=0; j<max_size; j += max_len){
            for(k=save_index + j + 1; k < max_len + j; ++k){
                save_data[k-1] = save_data[k];
                save_data[k] = 0;
            }
        }
    }
}
initContainer()
void initContainer (int width, int height, container * item)
Definition at line 3 of file container.c.
References container::data, container::len, and container::size.
Referenced by createCross(), createDot(), createL1(), createL2(), createLine(), createU(), and main().
                                                          {
    item->len = width;
    item->size = width * height;
    item->data = malloc(item->size * sizeof(char));
    for (int i = 0; i < item->size; ++i)
    {
        item->data[i] = 0;
    }
}
place()
void place (container * grid, container * piece, int x, int y)
Definition at line 137 of file container.c.
References container::data, container::len, and container::size.
Referenced by main().
                                                              {
    for (int i = 0; i < piece->size/piece->len; i++) {
        for (int j = 0; j < piece->len; j++) {
            if (piece->data[(i*piece->len)+j] != 0) {
                grid->data[((i+y)*grid->len)+j+x] = piece->data[(i*piece->
      len)+j];
            }
        }
    }
}
randomPiece()
container randomPiece ()
Definition at line 13 of file container.c.
References createCross(), createDot(), createL1(), createL2(), createLine(), and createU().
Referenced by main().
                       {
    container piece;
    srand(time(NULL));
    int random = rand() % 6;
    switch (random){
        case 0 :
            piece = createU();
            return piece;
        case 1 :
            piece = createL1();
            return piece;
        case 2 :
            piece = createL2();
            return piece;
        case 3 :
            piece = createCross();
            return piece;
        case 4:
            piece = createDot();
            return piece;
        case 5 :
            piece = createLine();
            return piece;
        default :
            printf("Error : could not generate cooresponding piece for int : %d \n", random);
            exit(0);
    }
}
rotate_180()
void rotate_180 (container * piece)
Definition at line 36 of file user.c.
References container::data, container::len, and container::size.
{
    int i,j,width,height;
    width=piece->size/piece->len;
    height=piece->len;
    char * tmp=malloc(sizeof(char)*width*height);
    for(i=0;i<width;i++)
        for(j=0;j<height;j++)
            tmp[i*width+j]=piece->data[i+width*j];
    for(i=0;i<width;i++)
        for(j=0;j<height;j++)
            piece->data[i*width+j]=tmp[i*width+j];
    free(tmp);
}
rotate_90()
void rotate_90 (container * piece)
Definition at line 52 of file user.c.
References container::data, container::len, and container::size.
{
    int i,j,width,height;
    width=piece->size/piece->len;
    height=piece->len;
    char * tmp=malloc(sizeof(char)*width*height);
    for(i=0;i<width;i++)
        for(j=0;j<height;j++)
          if(j== 0)
                tmp[i*width+j]=piece->data[width*(width-1)+i];
            else if (j>0 && j <width)
                tmp[i*width+j]=piece->data[width*j+i];
            else if(j == width)
                     tmp[i*width+j]=piece->data [width-i];
    for(i=0;i<width;i++)
        for(j=0;j<height;j++)
            piece->data[i*width+j]=tmp[i*width+j];
    free(tmp);
}
update()
void update (container * grid)
Definition at line 164 of file update.c.
References deleteCol(), deleteRow(), detectCol(), detectRow(), and gravity().
Referenced by main().
                            {
    int *index_list_row, *index_list_col;
    index_list_row = detectRow(grid);
    index_list_col = detectCol(grid);
    deleteRow(grid, index_list_row);
    deleteCol(grid, index_list_col);
    gravity(grid, index_list_row, index_list_col);
    free(index_list_row);
    free(index_list_col);
}