main.c File Reference
#include `head.h`
Functions
int main (int argc, char const *argv[])
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 3 of file main.c.
References checkCollision(), display(), HEIGHT, initContainer(), place(), randomPiece(), update(), and WIDTH.
                                      {
    container playGrid, playPiece;
    int pieceX, pieceY;
    initContainer(WIDTH, HEIGHT, &playGrid);
    playPiece = randomPiece();
    int tmp = 1;
    while(tmp){
        display(&playPiece);
        display(&playGrid);
        printf("Enter 'x y' of top left corner: ");
        scanf("%d %d", &pieceX, &pieceY);
        if (checkCollision(&playGrid, &playPiece, pieceX, pieceY)) {
            printf("Can't fit here!\n");
        }else{
            place(&playGrid, &playPiece, pieceX, pieceY);
            playPiece = randomPiece();
        }
        update(&playGrid);
    }
    return 0;
}