update.c File Reference
#include `head.h`
Functions
int * detectRow (container *grid)
char fullRow (container *grid, int index)
void deleteRow (container *grid, int *index_list)
int * detectCol (container *grid)
char fullCol (container *grid, int index)
void deleteCol (container *grid, int *index_list)
void gravity (container *grid, int *index_list_row, int *index_list_col)
void update (container *grid)
Function Documentation
deleteCol()
void deleteCol (container * grid, int * index_list)
Definition at line 108 of file update.c.
References container::data, container::len, and container::size.
Referenced by update().
                                                {
    int actual, max_len, max_size, max_size1, i, j;
    char *save_data;
    //Sauvegarde
    save_data = grid->data;
    max_len = grid->len;
    max_size1 = grid->size;
    max_size = index_list[0];
    for(i=1; i<max_size; ++i){
        actual = index_list[i];
        for(j=actual; j< max_size1; j += max_len){
            save_data[j] = 0;
        }
    }
}
deleteRow()
void deleteRow (container * grid, int * index_list)
Definition at line 44 of file update.c.
References container::data, and container::len.
Referenced by update().
                                                {
    int actual, max_len, max_size, i, j;
    char *save_data;
    //Sauvegarde
    save_data = grid->data;
    max_len = grid->len;
    max_size = index_list[0];
    for(i=1; i<max_size; ++i){
        actual = index_list[i];
        for(j=actual; j< actual + max_len; ++j){
            save_data[j] = 0;
        }
    }
}
detectCol()
int* detectCol (container * grid)
Definition at line 66 of file update.c.
References fullCol(), and container::len.
Referenced by update().
                               {
    int *index, actual, max_len, i;
    //save
    max_len = grid->len;
    //Index
    actual = 1;
    index = malloc((max_len+1)*sizeof(int));
    for(i=0; i<max_len; ++i){
        if(fullCol(grid, i)){
            index[actual] = i;
            ++actual;
        }
    }
    index[0] = actual;
    return realloc(index, actual);
}
detectRow()
int* detectRow (container * grid)
Definition at line 4 of file update.c.
References fullRow(), container::len, and container::size.
Referenced by update().
                               {
    int *index, actual, max_len, max_size, i;
    //Sauvegarde
    max_len = grid->len;
    max_size = grid->size;
    //Index
    actual = 1;
    index = malloc((max_size/max_len + 1)*sizeof(int));
    for(i=0; i<max_size; i += max_len){
        if(fullRow(grid, i)){
            index[actual] = i;
            ++actual;
        }
    }
    index[0] = actual;
    return realloc(index, actual);
}
fullCol()
char fullCol (container * grid, int index)
Definition at line 89 of file update.c.
References container::data, container::len, and container::size.
Referenced by detectCol().
                                        {
    int max_size, max_len, j;
    char* save_data;
    //save
    save_data = grid->data;
    max_size = grid->size;
    max_len = grid->len;
    for(j=index; j<max_size; j+=max_len){
        if(save_data[j] != 1) break;
    }
    if(j >= max_size){
        return 1;
    }
    return 0;
}
fullRow()
char fullRow (container * grid, int index)
Definition at line 27 of file update.c.
References container::data, and container::len.
Referenced by detectRow().
                                        {
    int max_len, j;
    char* save_data;
    save_data = grid->data;
    max_len = grid->len;
    for(j=index; j< index + max_len; ++j){
        if(save_data[j] != 1) break;
    }
    if(j == index + max_len){
        return 1;
    }
    return 0;
}
gravity()
void gravity (container * grid, int * index_list_row, int * index_list_col)
Definition at line 130 of file update.c.
References container::data, container::len, and container::size.
Referenced by update().
                                                                       {
    int max_len, max_size, save_size, save_index, i, j, k;
    char *save_data;
    //Save
    save_data = grid->data;
    max_size = grid->size;
    max_len = grid->len;
    //Update row
    save_size = index_list_row[0];
    for(i=1; i<save_size; ++i){
        for(j=index_list_row[i]-1; j>=0; --j){
            save_data[j+max_len] = save_data[j];
            save_data[j] = 0;
        }
    }
    //Update Col
    save_size = index_list_col[0];
    for(i=save_size-1; i>=1; --i){
        save_index = index_list_col[i];
        for(j=0; j<max_size; j += max_len){
            for(k=save_index + j + 1; k < max_len + j; ++k){
                save_data[k-1] = save_data[k];
                save_data[k] = 0;
            }
        }
    }
}
update()
void update (container * grid)
Definition at line 164 of file update.c.
References deleteCol(), deleteRow(), detectCol(), detectRow(), and gravity().
Referenced by main().
                            {
    int *index_list_row, *index_list_col;
    index_list_row = detectRow(grid);
    index_list_col = detectCol(grid);
    deleteRow(grid, index_list_row);
    deleteCol(grid, index_list_col);
    gravity(grid, index_list_row, index_list_col);
    free(index_list_row);
    free(index_list_col);
}